function [key,familyHash]=featureCacheKey(F,method,parameters,cfg,mode,snrs,realizations)
%FEATURECACHEKEY Bind actual inputs, code and numerical software versions.
familyHash=eba.hash(jsonencode(table2struct(F)));scientific=rmfield(cfg,{'root','output'});
sources={'+eba/features.m','+eba/record.m','+eba/recordId.m','+eba/waveform.m', ...
    '+eba/noise.m','+eba/hash.m','+eba/featureCacheKey.m'};
digests=cellfun(@(p) eba.hash(fullfile(cfg.root,p),'file'),sources,'UniformOutput',false);
key=eba.hash(jsonencode(struct('cache_protocol','2.1.0','families',familyHash,'method',method,'parameters',parameters, ...
    'snrs',snrs,'realizations',realizations,'mode',mode,'source_files',{sources},'source_sha256',{digests}, ...
    'config_sha256',eba.hash(fullfile(cfg.root,'config','research_v2.json'),'file'), ...
    'actual_config_sha256',eba.hash(jsonencode(scientific)),'MATLAB_version',version, ...
    'toolbox_versions_sha256',eba.hash(jsonencode(ver)))));
end
