function [model,report] = rawTrain(F,cfg,kind,seed)
%RAWTRAIN Development-only native CPU training with family-disjoint calibration.
assert(istable(F) && height(F)>0 && all(ismember({'family_id','split','class_id'},F.Properties.VariableNames)), ...
    'eba:RawFamilies','Development family metadata is required.');
assert(all(string(F.split)~="test"),'eba:TestFirewall','Raw training cannot receive test families.');
assert(all(ismember(string(F.split),["train" "validation"])),'eba:RawFamilies','Only train/validation splits are accepted.');
assert(numel(unique(string(F.family_id)))==height(F),'eba:FamilyLeakage','Raw families must have unique identities.');
K=cfg.primary_class_count;
assert(K==9 && all(ismember(F.class_id,1:K)),'eba:RawClasses','This raw comparison requires the nine primary classes.');
assert(isscalar(seed) && isfinite(seed) && seed>=0 && seed<2^32 && seed==fix(seed),'eba:RawSeed','Invalid model seed.');
[S,calibrationIDs]=eba.subsetFamilies(F,max(cfg.learning_train_families_per_cell),3);
fitFamilies=S(S.split=="train" & ~ismember(S.family_id,calibrationIDs),:);
calibrationFamilies=S(ismember(S.family_id,calibrationIDs),:);
validationFamilies=S(S.split=="validation",:);
assert(isempty(intersect(fitFamilies.family_id,calibrationFamilies.family_id)) && ...
    isempty(intersect(fitFamilies.family_id,validationFamilies.family_id)) && ...
    isempty(intersect(calibrationFamilies.family_id,validationFamilies.family_id)), ...
    'eba:FamilyLeakage','Fitting, calibration and validation families overlap.');
for subset={fitFamilies,calibrationFamilies,validationFamilies}
    assert(isequal(unique(subset{1}.class_id),(1:K)'),'eba:RawClasses','Every primary class must remain in fitting, calibration and validation.');
end
N=round(cfg.Fs*cfg.clip_duration_s); epochs=20; structuralTest=false;
if isfield(cfg,'raw_test')
    assert(isstruct(cfg.raw_test) && isfield(cfg.raw_test,'max_epochs') && isfield(cfg.raw_test,'sequence_samples'), ...
        'eba:RawTest','Structural test controls require epoch count and sample length.');
    epochs=cfg.raw_test.max_epochs; N=cfg.raw_test.sequence_samples; structuralTest=true;
    assert(isscalar(epochs) && epochs==1 && isscalar(N) && any(N==[500 1000]), ...
        'eba:RawTest','Structural tests use one epoch and only 500 or 1000 samples.');
end
startup=eba.processMemory(); old=rng; restore=onCleanup(@() rng(old)); rng(seed,'twister');
[net,architecture]=eba.rawArchitecture(kind,K,N);
[Xfit,yfit,Pfit]=records(fitFamilies,cfg,N);
[Xcal,ycal,Pcal]=records(calibrationFamilies,cfg,N);
[Xval,yval,Pval]=records(validationFamilies,cfg,N);
classNames=cellstr(compose('class%02d',1:K));
targets=categorical(yfit,1:K,classNames); validationTargets=categorical(yval,1:K,classNames);
frequency=ceil(numel(yfit)/64);
options=trainingOptions('adam','MaxEpochs',epochs,'MiniBatchSize',64,'InitialLearnRate',.001, ...
    'Shuffle','every-epoch','ValidationData',{Xval,validationTargets},'ValidationFrequency',frequency, ...
    'ValidationPatience',5,'ObjectiveMetricName','loss','OutputNetwork','best-validation', ...
    'InputDataFormats','CTB','ExecutionEnvironment','cpu','Plots','none','Verbose',false);
timer=tic; [net,info]=trainnet(Xfit,targets,net,'crossentropy',options); trainingSeconds=toc(timer);
assert(isa(info,'deep.TrainingInfo') && istable(info.TrainingHistory) && istable(info.ValidationHistory) && ...
    all(ismember({'Iteration','Epoch','Loss'},info.TrainingHistory.Properties.VariableNames)) && ...
    all(ismember({'Iteration','Loss'},info.ValidationHistory.Properties.VariableNames)) && ...
    height(info.TrainingHistory)>0 && height(info.ValidationHistory)>0, ...
    'eba:RawTrainingInfo','R2026b training history is missing actual training or validation.');
assert(all(isfinite(info.TrainingHistory.Loss)) && all(isfinite(info.ValidationHistory.Loss)) && ...
    any(string(info.StopReason)==["Max epochs completed" "Met validation criterion"]), ...
    'eba:RawTrainingFailure','Raw training stopped with invalid loss or an unexpected reason.');
model=struct('network',net,'kind',upper(string(kind)),'classes',(1:K)','sequence_samples',N, ...
    'Fs_hz',cfg.Fs,'temperature',1,'calibrated',false,'seed',seed,'architecture',architecture, ...
    'training_time_s',trainingSeconds,'input_normalization','none','structural_test_only',structuralTest, ...
    'fit_family_ids',fitFamilies.family_id,'calibration_family_ids',calibrationFamilies.family_id, ...
    'validation_family_ids',validationFamilies.family_id,'dataset_version',cfg.dataset_version);
[~,~,~,scores]=eba.rawPredict(model,Xcal); objective=@(logT) nll(scores,ycal,exp(logT));
logT=fminbnd(objective,-5,4); model.temperature=exp(logT); model.calibrated=true;
model.calibration=struct('temperature',model.temperature,'n_records',numel(ycal),'n_families',height(calibrationFamilies), ...
    'family_hash',eba.hash(strjoin(sort(calibrationFamilies.family_id),newline)), ...
    'nll_uncalibrated',objective(0),'nll_calibrated',objective(logT), ...
    'scope','reserved training families excluded from fitting; temperature NLL only');
[predicted,confidence,probabilities,rawScores]=eba.rawPredict(model,Xval);
validationMetrics=eba.metrics(yval,predicted,K);
truth=zeros(size(probabilities)); truth(sub2ind(size(truth),(1:numel(yval))',yval))=1;
validationBrier=mean(sum((probabilities-truth).^2,2));
snapshot=eba.processMemory(); tmp=[tempname '.mat']; save(tmp,'model','-v7'); bytes=dir(tmp); delete(tmp);
bestLoss=min(info.ValidationHistory.Loss); bestRows=info.ValidationHistory.Loss==bestLoss;
Pval.predicted_class=predicted; Pval.confidence=confidence;
report=struct('kind',char(upper(string(kind))),'seed',seed,'status','development_raw_baseline', ...
    'structural_test_only',structuralTest,'architecture',architecture,'n_fit_families',height(fitFamilies), ...
    'n_calibration_families',height(calibrationFamilies),'n_validation_families',height(validationFamilies), ...
    'n_fit_records',numel(yfit),'n_calibration_records',numel(ycal),'n_validation_records',numel(yval), ...
    'augmentation_snr_db',[Inf 20 5],'augmentation_realization',1,'input_normalization','none', ...
    'optimizer','Adam','initial_learning_rate',.001,'maximum_epochs',epochs,'mini_batch_size',64, ...
    'validation_frequency',frequency,'validation_patience',5,'validation_usage','early_stopping_only', ...
    'epochs_completed',max(info.TrainingHistory.Epoch),'iterations_completed',max(info.TrainingHistory.Iteration), ...
    'output_network_iteration',info.OutputNetworkIteration,'best_validation_loss',bestLoss, ...
    'best_validation_iterations',info.ValidationHistory.Iteration(bestRows),'stop_reason',char(info.StopReason), ...
    'training_history',table2struct(info.TrainingHistory),'validation_history',table2struct(info.ValidationHistory), ...
    'training_time_s',trainingSeconds,'model_serialized_bytes',bytes.bytes,'execution_environment','cpu', ...
    'startup_RSS_bytes',startup.rss_bytes,'process_VmHWM_bytes',snapshot.hwm_bytes, ...
    'memory_provenance','Linux /proc/self/status; VmHWM is entire MATLAB-session high-water upper bound, not isolated model peak', ...
    'family_parameters_sha256',eba.hash(jsonencode(table2struct(S))), ...
    'fit_family_ids',fitFamilies.family_id,'calibration_family_ids',calibrationFamilies.family_id, ...
    'validation_family_ids',validationFamilies.family_id,'fit_records',table2struct(Pfit), ...
    'calibration_records',table2struct(Pcal),'validation_predictions',table2struct(Pval), ...
    'calibration',model.calibration,'validation_metrics',validationMetrics,'validation_brier',validationBrier, ...
    'validation_probabilities',probabilities,'validation_raw_scores',rawScores,'test_evaluated',false);
end

function [X,y,P]=records(F,cfg,N)
n=height(F)*3; X=cell(n,1); y=zeros(n,1);
P=table('Size',[n 5],'VariableTypes',{'string','double','double','double','string'}, ...
    'VariableNames',{'family_id','class_id','SNR_db','noise_seed','waveform_sha256'});
k=0;
for i=1:height(F)
    for snr=[Inf 20 5]
        [x,m]=eba.record(F(i,:),snr,1,cfg,'development');
        assert(N<=numel(x),'eba:RawInput','Fitted sequence exceeds waveform length.');
        k=k+1; X{k}=single(x(1:N)'); y(k)=F.class_id(i);
        P(k,:)={F.family_id(i),F.class_id(i),snr,m.noise_seed,m.waveform_sha256};
    end
end
end

function value=nll(scores,y,T)
a=scores/T; a=a-max(a,[],2); logp=a-log(sum(exp(a),2));
value=-mean(logp(sub2ind(size(logp),(1:size(logp,1))',y)));
end

