function [hp,comparison]=sharedHyperparameters(searches,methods)
%SHAREDHYPERPARAMETERS One controlled classifier configuration across representations.
methods=string(methods(:));assert(iscell(searches) && numel(searches)==numel(methods) && ...
    ~isempty(methods) && numel(unique(methods))==numel(methods), ...
    'eba:SharedClassifier','One search table per unique representation is required.');
values=[];grid=[];
for m=1:numel(methods)
    t=searches{m};assert(istable(t) && height(t)>0 && all(ismember( ...
        {'hyperparameters_json','validation_macro_f1'},t.Properties.VariableNames)), ...
        'eba:SharedClassifier','Search tables require explicit candidates and validation scores.');
    if m==1,grid=string(t.hyperparameters_json);values=zeros(height(t),numel(methods));end
    assert(isequal(grid,string(t.hyperparameters_json)) && numel(unique(grid))==numel(grid) && ...
        all(isfinite(t.validation_macro_f1) & t.validation_macro_f1>=0 & t.validation_macro_f1<=1), ...
        'eba:SharedClassifier','Every representation must evaluate the same unique ordered grid with valid scores.');
    values(:,m)=t.validation_macro_f1;
end
average=mean(values,2);best=1;
for h=2:numel(average),if average(h)>average(best)+1e-12,best=h;end;end
hp=jsondecode(grid(best));comparison=table(grid,average,(1:numel(average))'==best, ...
    'VariableNames',{'hyperparameters_json','mean_validation_macro_f1','selected'});
comparison=[comparison,array2table(values,'VariableNames',cellstr("validation_macro_f1_"+lower(methods)))];
end
