function cfg = defaultConfig()
%DEFAULTCONFIG Reproducible configuration for M1-M11.

root = fileparts(fileparts(mfilename('fullpath')));
cfg = struct();
cfg.package_version = "legacy-dsp-v0.1.0";
cfg.project_root = root;
cfg.seed = 20260926;

datasetRoot = string(getenv("PQ_DATASET_ROOT"));
cfg.dataset = struct( ...
    'root', datasetRoot, ...
    'metadata_file', "metadata.csv", ...
    'signals_subdir', "signals", ...
    'required_columns', {{ ...
        'signal_id','label','severity','Fs','duration_s','n_samples', ...
        'SNR_db','event_start_s','event_end_s','seed','split', ...
        'family_id','file','parameters_json'}});

cfg.nominal_frequency_hz = 60;
cfg.methods = {'FFT','STFT','DWT','CWT','ST'};

cfg.fft = struct( ...
    'harmonic_orders', 2:9);

cfg.stft = struct( ...
    'window_size', 512, ...
    'overlap', 256, ...
    'window_type', "blackman");

cfg.dwt = struct( ...
    'candidate_wavelets', {{'db4','db6','db8','sym4','sym6','coif3','coif5'}}, ...
    'candidate_levels', 3:7, ...
    'selected_wavelet', "db4", ...
    'selected_level', 5, ...
    'selection_runtime_weight', 0.10);

cfg.cwt = struct( ...
    'voices_per_octave', 12, ...
    'min_frequency_hz', 30, ...
    'max_frequency_hz', 4000);

cfg.st = struct( ...
    'min_frequency_hz', 30, ...
    'max_frequency_hz', 4000, ...
    'num_log_frequencies', 64, ...
    'gaussian_sigma_factor', 1.0, ...
    'truncate_sigma', 4.0);

cfg.event = struct( ...
    'smooth_ms', 5, ...
    'threshold_mad', 5.0, ...
    'min_event_ms', 0.2);

cfg.classifier = struct( ...
    'type', "svm_ecoc", ...
    'standardize', true);

cfg.benchmark = struct( ...
    'timing_repeats', 3, ...
    'warmup_repeats', 1, ...
    'max_records_complexity', 18);

cfg.statistics = struct( ...
    'bootstrap_reps', 1000, ...
    'alpha', 0.05);

cfg.output = struct( ...
    'root', fullfile(root,'results'), ...
    'cache', fullfile(root,'cache'), ...
    'features', fullfile(root,'results','features'), ...
    'models', fullfile(root,'results','models'), ...
    'metrics', fullfile(root,'results','metrics'), ...
    'figures', fullfile(root,'results','figures'), ...
    'manifests', fullfile(root,'results','manifests'));
end
