function report=run_six_model_runtime(classifier,method)
%RUN_SIX_MODEL_RUNTIME Fresh-session matched runtime for a retained six-track candidate.
cfg=eba.config();classifier=upper(string(classifier));method=upper(string(method));
assert(any((classifier=="SVM" & method==["FFT","STFT","DWT"]) | ...
    (classifier=="RF" & method==["FFT","ST","CWT"])), ...
    'eba:SixRuntimeCandidate','Candidate is outside the fixed six-model comparison.');
if classifier=="SVM"
    path=fullfile(cfg.output,'stream_models',"reselection_stream_full_"+lower(method)+".mat");
    s=load(path,'model');model=s.model;
else
    path=fullfile(cfg.output,'six_model_stream',"model_rf_"+lower(method)+".mat");
    s=load(path,'model');model=s.model;
end
assert(string(model.kind)==classifier&&string(model.method)==method,'eba:SixRuntimeModel','Model identity mismatch.');
F=eba.families(cfg.families_per_cell,cfg);V=F(F.split=="validation",:);ids=zeros(numel(cfg.classes)-1,1);
for c=2:numel(cfg.classes),ids(c-1)=find(V.class_id==c & V.severity_stratum==3 & V.duration_stratum==4,1);end
assert(all(ids>0),'eba:SixRuntimeWorkload','Matched runtime requires one validation family per event class.');
schedule=eba.continuousSchedule(V(ids,:),cfg,20,"runtime_shared_sequence",cfg.stream_seed+90000);
signal=eba.continuousSignal(schedule,(0:schedule.n_samples-1)',cfg);
firstEnd=round(cfg.Fs*max(cfg.stream_window_cycles)/cfg.nominal_frequency_hz);
ends=round(linspace(firstEnd,schedule.n_samples,cfg.runtime_repetitions));
assert(all(diff(ends)>0)&&model.window_samples<=firstEnd,'eba:SixRuntimeWorkload','Invalid matched decision endpoints.');
before=eba.processMemory();
for k=1:cfg.runtime_warmups
    idx=ends(k)-model.window_samples+1:ends(k);x=signal(idx);v=eba.features(x,cfg.Fs,method,model.parameters);
    label=eba.predict(model,v);eba.severity(x,cfg.classes(label),cfg.Fs);
end
values=zeros(numel(ends),5);representation=zeros(numel(ends),1);
for k=1:numel(ends)
    total=tic;idx=ends(k)-model.window_samples+1:ends(k);x=signal(idx);
    timer=tic;[v,~,bytes]=eba.features(x,cfg.Fs,method,model.parameters);feature=toc(timer);
    timer=tic;[label,confidence]=eba.predict(model,v);classification=toc(timer);
    timer=tic;[grade,physical]=eba.severity(x,cfg.classes(label),cfg.Fs);severity=toc(timer);
    pred=struct('window_start_s',(idx(1)-1)/cfg.Fs,'window_end_s',ends(k)/cfg.Fs, ...
        'decision_time_s',ends(k)/cfg.Fs,'class_id',label,'confidence',confidence, ...
        'severity',grade,'voltage_rms_pu_min',physical.voltage_rms_pu_min);
    timer=tic;eba.stateStep([],pred,struct('threshold_on',.7,'threshold_off',.5,'min_windows',2, ...
        'min_evidence_s',1/60,'recovery_windows',2,'refractory_s',0,'classes',cfg.classes, ...
        'method_version',cfg.method_version,'model_version',model.model_version, ...
        'dataset_version',cfg.dataset_version,'git_commit',model.training_git_commit, ...
        'sequence_id','runtime','confidence_calibrated',true));state=toc(timer);
    values(k,:)=[feature,classification,severity,state,toc(total)];representation(k)=bytes;
end
after=eba.processMemory();q=quantile(values,[.5 .95 .99]);D=dir(path);
report=struct('classifier',classifier,'method',method,'model_sha256',eba.hash(path,'file'), ...
    'model_serialized_bytes',D.bytes,'window_samples',model.window_samples,'window_cycles',model.window_cycles, ...
    'hop_samples',model.hop_samples,'n_repetitions',numel(ends),'warmups',cfg.runtime_warmups, ...
    'feature_median_s',q(1,1),'feature_p95_s',q(2,1),'feature_p99_s',q(3,1), ...
    'classification_median_s',q(1,2),'classification_p95_s',q(2,2),'classification_p99_s',q(3,2), ...
    'severity_median_s',q(1,3),'severity_p95_s',q(2,3),'severity_p99_s',q(3,3), ...
    'state_median_s',q(1,4),'state_p95_s',q(2,4),'state_p99_s',q(3,4), ...
    'total_median_s',q(1,5),'total_p95_s',q(2,5),'total_p99_s',q(3,5), ...
    'streaming_real_time_factor_p95',q(2,5)/(model.hop_samples/cfg.Fs), ...
    'throughput_windows_per_s',numel(ends)/sum(values(:,5)), ...
    'throughput_input_samples_per_s',model.hop_samples*numel(ends)/sum(values(:,5)), ...
    'representation_bytes_median',median(representation),'startup_and_model_RSS_bytes',before.rss_bytes, ...
    'peak_process_RSS_bytes',after.hwm_bytes,'shared_signal_sha256',eba.hash(signal,'numeric'), ...
    'shared_endpoints_sha256',eba.hash(ends,'numeric'), ...
    'policy','Fresh MATLAB process; matched signal/endpoints; candidate-specific trailing window; two warmups; 100 repetitions; compute-only, no model load or data generation in timing', ...
    'memory_scope','Whole MATLAB process high-water RSS, not isolated model allocation');
out=fullfile(cfg.output,'six_model_stream',"runtime_"+lower(classifier)+"_"+lower(method)+".json");
eba.json(out,report);writetable(array2table([values,representation],'VariableNames', ...
    {'feature_s','classification_s','severity_s','state_s','total_s','representation_bytes'}), ...
    replace(out,'.json','.csv'));
eba.manifest("six_model_runtime_"+lower(classifier)+"_"+lower(method),cfg, ...
    struct('classifier',classifier,'method',method,'shared_signal_sha256',report.shared_signal_sha256, ...
    'shared_endpoints_sha256',report.shared_endpoints_sha256,'repetitions',report.n_repetitions, ...
    'warmups',report.warmups),{out,replace(out,'.json','.csv'),path});
fprintf('SIX_MODEL_RUNTIME_PASS classifier=%s method=%s p95_ms=%.3f RTF=%.4f\n', ...
    classifier,method,1000*report.total_p95_s,report.streaming_real_time_factor_p95);
end
