function report=run_validation_model_selection()
%RUN_VALIDATION_MODEL_SELECTION Select separate offline and continuous leaders; never reads test.
cfg=eba.config();methods=["FFT","STFT","DWT","CWT","ST"];
[status,sha]=system('git rev-parse HEAD');assert(status==0);sha=strtrim(sha);
[~,dirty]=system('git status --porcelain --untracked-files=normal');
assert(isempty(strtrim(dirty)),'eba:SelectionSource','Selection requires a clean committed source tree.');
state=load(fullfile(cfg.output,'reselection_state_refinement.mat'),'retained');
expected=string(cellfun(@(q) q.model.method,state.retained(~cellfun(@isempty,state.retained)),'UniformOutput',false));
assert(~isempty(expected),'eba:SelectionCandidates','No refined stream candidates were retained.');
S=load(fullfile(cfg.output,'reselection_stream_full_development.mat'),'retained','summary');
eba.requireCandidateCoverage(expected,string(S.summary.method),'Full validation selection');
classification=readtable(fullfile(cfg.output,'validation_svm_metrics.csv'),'TextType','string');
stats=load(fullfile(cfg.output,'validation_svm_statistics.mat'),'details');
robust=stats.details.robustness_summary;
rows=cell(numel(methods),1);runtimeCommit="";signalHash="";endpointsHash="";artifacts=strings(0,1);
for m=1:numel(methods)
    off=find(classification.method==methods(m));rob=find(string(robust.method)==methods(m));
    assert(isscalar(off)&&isscalar(rob),'eba:SelectionOffline','Every offline SVM method must remain in the report.');
    base=[{methods(m),classification.macro_f1(off),classification.macro_f1_ci_low(off), ...
        classification.macro_f1_ci_high(off)},num2cell(nan(1,13)),{""},num2cell(false(1,4))];
    if ~any(expected==methods(m))
        rows{m}=table(base{:},'VariableNames',names());continue
    end
    ix=find(string(S.summary.method)==methods(m));assert(isscalar(ix)&&~isempty(S.retained{m}));
    id="runtime_reselection_stream_"+lower(methods(m));
    runtimePath=fullfile(cfg.output,id+".json");runtimeManifestPath=fullfile(cfg.output,'manifests',id+".json");
    R=jsondecode(fileread(runtimePath));RM=verifyManifest(runtimeManifestPath,cfg);
    if runtimeCommit==""
        runtimeCommit=string(RM.git_commit);signalHash=string(R.shared_signal_sha256);
        endpointsHash=string(R.shared_endpoints_sha256);
    end
    assert(string(RM.git_commit)==runtimeCommit && string(R.shared_signal_sha256)==signalHash && ...
        string(R.shared_endpoints_sha256)==endpointsHash && R.n_repetitions==cfg.runtime_repetitions && ...
        R.warmups==cfg.runtime_warmups,'eba:SelectionRuntime','Runtime candidates must share commit, physical signal, endpoints and policy.');
    modelPath=fullfile(cfg.root,R.model_path);stored=load(modelPath,'model');model=stored.model;
    assert(strcmp(eba.hash(modelPath,'file'),R.model_sha256) && string(model.method)==methods(m), ...
        'eba:SelectionModel','Measured runtime model does not match the validated candidate.');
    fullPath=fullfile(cfg.output,"reselection_stream_full_validation_"+lower(methods(m))+".json");
    V=jsondecode(fileread(fullPath));row=S.summary(ix,:);
    assert(V.n_sequences==6048 && V.n_independent_clusters==864 && ...
        abs(V.f1-row.event_f1)<1e-12 && isfinite(R.streaming_real_time_factor_p95), ...
        'eba:SelectionValidation','Full validation report and candidate summary disagree.');
    feasible=logical(row.eligible)&&R.streaming_real_time_factor_p95<=1;
    values=base;values(5:19)={V.f1,V.f1_ci_low,V.f1_ci_high,V.recall,V.missed_event_rate, ...
        V.false_alarms_per_minute,V.false_alarms_per_minute_ci_low,V.false_alarms_per_minute_ci_high, ...
        V.mean_latency_s,R.total_p95_s,R.streaming_real_time_factor_p95,R.peak_process_RSS_bytes, ...
        R.model_serialized_bytes,string(model.training_git_commit),feasible};
    rows{m}=table(values{:},'VariableNames',names());
    artifacts=[artifacts;string(fullPath);string(runtimePath);string(runtimeManifestPath); ...
        string(erase(modelPath,[cfg.root filesep]))]; %#ok<AGROW>
end
result=vertcat(rows{:});selection=table(result.event_f1,result.false_alarms_per_minute, ...
    result.matched_latency_s,result.stream_RTF_p95,result.stream_feasible, ...
    'VariableNames',{'event_f1','false_alarms_per_minute','matched_latency_s','stream_RTF_p95','eligible'});
[winner,front]=eba.selectStreamCandidate(selection);result.pareto=front;
fullManifest=verifyManifest(fullfile(cfg.output,'manifests','reselection_stream_full_development.json'),cfg);
assert(string(fullManifest.git_commit)==runtimeCommit && ...
    isequal(sort(string(fullManifest.extra.methods(:))),sort(expected(:))), ...
    'eba:SelectionProvenance','Full validation and matched runtime must bind the same complete source/candidate set.');
[~,offlineOrder]=sortrows([-result.offline_svm_macro_f1,(1:height(result))'],[1 2]);offlineWinner=offlineOrder(1);
result.selected_offline=false(height(result),1);result.selected_offline(offlineWinner)=true;
result.selected_stream=false(height(result),1);result.selected_stream(winner)=true;
report=struct('status','PASS','scope','validation only; test not accessed', ...
    'selected_stream_method',result.method(winner),'selected_stream_classifier','SVM', ...
    'selected_stream_event_f1',result.event_f1(winner), ...
    'selected_stream_false_alarms_per_minute',result.false_alarms_per_minute(winner), ...
    'selected_stream_RTF_p95',result.stream_RTF_p95(winner), ...
    'selected_offline_method',result.method(offlineWinner),'selected_offline_classifier','SVM', ...
    'selected_offline_macro_f1',result.offline_svm_macro_f1(offlineWinner), ...
    'rule','Separate offline and continuous leaders. For streaming, require complete full validation and matched-session p95 RTF<=1; retain event F1, false alarms/minute, latency and RTF on the Pareto front; maximize event F1, then minimize matched latency.', ...
    'methods',table2struct(result),'validation_source_commit',char(string(fullManifest.git_commit)), ...
    'runtime_source_commit',char(runtimeCommit),'selection_commit',sha,'test_accessed',false);
out=fullfile(cfg.output,'validation_model_selection.csv');json=fullfile(cfg.output,'validation_model_selection.json');
writetable(result,out);eba.json(json,report);
artifacts=[artifacts;string(out);string(json);fullfile(cfg.output,'reselection_stream_full_validation.csv'); ...
    fullfile(cfg.output,'reselection_stream_full_development.mat'); ...
    fullfile(cfg.output,'manifests','reselection_stream_full_development.json'); ...
    fullfile(cfg.output,'reselection_state_refinement.mat'); ...
    fullfile(cfg.output,'validation_svm_metrics.csv');fullfile(cfg.output,'validation_svm_statistics.mat')];
eba.manifest('validation_model_selection',cfg,struct('scope',report.scope,'selection_rule',report.rule, ...
    'selected_stream_method',report.selected_stream_method,'selected_offline_method',report.selected_offline_method, ...
    'candidate_methods',expected,'runtime_source_commit',runtimeCommit,'test_accessed',false),artifacts);
fprintf('STREAM_MODEL_SELECTION_PASS selected_stream=%s eventF1=%.6f RTF_p95=%.6f selected_offline=%s macroF1=%.6f test_accessed=0\n', ...
    result.method(winner),result.event_f1(winner),result.stream_RTF_p95(winner), ...
    result.method(offlineWinner),result.offline_svm_macro_f1(offlineWinner));
end

function n=names()
n={'method','offline_svm_macro_f1','offline_macro_f1_ci_low','offline_macro_f1_ci_high', ...
    'event_f1','event_f1_ci_low','event_f1_ci_high','event_recall','missed_event_rate', ...
    'false_alarms_per_minute','false_alarms_ci_low','false_alarms_ci_high','matched_latency_s', ...
    'inference_p95_s','stream_RTF_p95','peak_process_RSS_bytes','model_bytes','training_commit', ...
    'stream_feasible','pareto','selected_offline','selected_stream'};
end

function M=verifyManifest(path,cfg)
M=jsondecode(fileread(path));assert(M.repository_state_clean && ...
    strcmp(M.config_hash,eba.hash(fullfile(cfg.root,'config','research_v2.json'),'file')), ...
    'eba:SelectionManifest','Runtime manifest source/config is invalid.');
for i=1:numel(M.artifacts)
    a=M.artifacts(i);assert(strcmp(eba.hash(fullfile(cfg.root,a.path),'file'),a.sha256), ...
        'eba:SelectionArtifact','Runtime source artifact hash mismatch.');
end
end
