function report=run_six_model_selection()
%RUN_SIX_MODEL_SELECTION Select among six family-level models without an RTF cutoff.
cfg=eba.config();path=fullfile(cfg.output,'six_model_stream','six_model_stream_validation.csv');
assert(isfile(path),'eba:SixSelectionInputs','Run the six-model full validation first.');
T=readtable(path,'TextType','string');assert(height(T)==6 && all(T.complete), ...
    'eba:SixSelectionCoverage','All six stream candidates must have full validation.');
assert(sum(T.classifier=="SVM")==3&&sum(T.classifier=="RF")==3, ...
    'eba:SixSelectionTrack','Selection must retain the three light SVM and three heavy RF models.');
signalHashes=strings(6,1);endpointHashes=strings(6,1);runtimeFiles=strings(6,1);modelFiles=strings(6,1);
for i=1:height(T)
    if T.classifier(i)=="SVM"
        runtimeFile=fullfile(cfg.output,"runtime_reselection_stream_"+lower(T.method(i))+".json");
        modelFile=fullfile(cfg.output,'stream_models',"reselection_stream_full_"+lower(T.method(i))+".mat");
    else
        runtimeFile=fullfile(cfg.output,'six_model_stream',"runtime_rf_"+lower(T.method(i))+".json");
        modelFile=fullfile(cfg.output,'six_model_stream',"model_rf_"+lower(T.method(i))+".mat");
    end
    assert(isfile(runtimeFile)&&isfile(modelFile),'eba:SixSelectionRuntime','Every model needs a fresh-session runtime run.');
    R=jsondecode(fileread(runtimeFile));model=load(modelFile,'model');D=dir(modelFile);
    assert(string(model.model.kind)==T.classifier(i)&&string(model.model.method)==T.method(i)&& ...
        D.bytes>0,'eba:SixSelectionIdentity','Runtime model identity does not match the validation row.');
    if T.classifier(i)=="SVM"
        reportFile=fullfile(cfg.output,'six_model_stream',"validation_svm_"+lower(T.method(i))+".json");
    else
        reportFile=fullfile(cfg.output,'six_model_stream',"validation_rf_"+lower(T.method(i))+".json");
    end
    V=jsondecode(fileread(reportFile));
    assert(abs(V.f1-T.event_f1(i))<1e-12 && V.n_sequences==864 && ...
        V.n_independent_clusters==864,'eba:SixSelectionValidation','Validation report or workload does not match.');
    T.runtime_p95_s(i)=R.total_p95_s;T.runtime_p99_s(i)=R.total_p99_s;
    T.stream_RTF_p95(i)=R.streaming_real_time_factor_p95;
    T.throughput_windows_per_s(i)=R.throughput_windows_per_s;
    T.peak_process_RSS_bytes(i)=R.peak_process_RSS_bytes;
    T.model_bytes(i)=R.model_serialized_bytes;
    signalHashes(i)=string(R.shared_signal_sha256);endpointHashes(i)=string(R.shared_endpoints_sha256);
    runtimeFiles(i)=string(runtimeFile);modelFiles(i)=string(modelFile);
end
assert(numel(unique(signalHashes))==1&&numel(unique(endpointHashes))==1, ...
    'eba:SixSelectionPairing','All six runtime tests must use the same signal and physical decision endpoints.');
selection=table(T.event_f1,T.event_f1_ci_low,T.false_alarms_per_minute,T.matched_latency_s, ...
    T.stream_RTF_p95,T.model_bytes,T.complete,'VariableNames', ...
    {'event_f1','event_f1_ci_low','false_alarms_per_minute','matched_latency_s','stream_RTF_p95','model_bytes','eligible'});
[winner,front]=eba.selectStreamCandidate(selection);T.pareto=front;
T.selected=false(height(T),1);T.selected(winner)=true;
report=struct('status','PASS','scope','12-class validation; six matched pipelines; 864 independent families; one 20 dB realization per family; test not accessed', ...
    'n_sequences',864,'n_independent_clusters',864,'noise_snr_db',20,'noise_realization',1, ...
    'selected_method',T.method(winner),'selected_classifier',T.classifier(winner), ...
    'selected_event_f1',T.event_f1(winner),'selected_event_f1_ci_low',T.event_f1_ci_low(winner), ...
    'selected_false_alarms_per_minute',T.false_alarms_per_minute(winner), ...
    'selected_latency_s',T.matched_latency_s(winner),'selected_runtime_p95_s',T.runtime_p95_s(winner), ...
    'selected_stream_RTF_p95',T.stream_RTF_p95(winner), ...
    'rule','No latency or model-size exclusion. All complete candidates remain eligible; report the Pareto front in Event F1, false alarms/minute, matched latency, RTF and model size; select the largest grouped-family/schedule bootstrap 95% lower Event F1 bound, then point Event F1, then fewer false alarms and shorter latency.', ...
    'runtime_signal_sha256',signalHashes(1),'runtime_endpoints_sha256',endpointHashes(1), ...
    'test_accessed',false,'rows',table2struct(T),'runtime_files',runtimeFiles,'model_files',modelFiles);
out=fullfile(cfg.output,'six_model_stream','six_model_selection.csv');writetable(T,out);
json=fullfile(cfg.output,'six_model_stream','six_model_selection.json');eba.json(json,report);
eba.manifest('six_model_selection',cfg,struct('scope',report.scope,'selected_method',report.selected_method, ...
    'selected_classifier',report.selected_classifier,'selection_rule',report.rule, ...
    'runtime_signal_sha256',signalHashes(1),'runtime_endpoints_sha256',endpointHashes(1), ...
    'test_accessed',false),[string(out);string(json);runtimeFiles;modelFiles]);
fprintf('SIX_MODEL_SELECTION_PASS selected=%s_%s eventF1=%.6f RTF=%.4f Pareto=%d test_accessed=0\n', ...
    T.method(winner),T.classifier(winner),T.event_f1(winner),T.stream_RTF_p95(winner),sum(front));
end
