%% Complete M1-M11 execution (can be computationally expensive)
steps={ ...
 '00_preflight.m','01_m1_review.m','02_m2_dwt_select.m','03_m3_cwt_smoke.m', ...
 '04_m4_st_smoke.m','05_m5_extract_features.m','06_m6_train_classifier.m', ...
 '07_m7_classification_metrics.m','08_m8_temporal_metrics.m','09_m9_complexity.m', ...
 '10_m10_noise_robustness.m','11_m11_statistics_pareto.m'};
here=fileparts(mfilename('fullpath'));
for k=1:numel(steps)
    fprintf('\n\n######## %s ########\n',steps{k});
    run(fullfile(here,steps{k}));
end
fprintf('\nLEGACY_PIPELINE_COMPLETE\n');
