function report=run_confirmed_event_demo()
%RUN_CONFIRMED_EVENT_DEMO Frozen causal illustration; ends at first confirmed event.
cfg=eba.config();freeze=eba.requireFrozen(cfg,'begin');cleanup=onCleanup(@() eba.requireFrozen(cfg,'reset'));
assert(isfield(freeze,'selected_stream') && isfield(freeze,'demo'),'eba:TestFirewall','Freeze the validated illustration before test.');
entry=freeze.selected_stream;M=load(fullfile(cfg.root,entry.path),'model');model=M.model;
F=eba.families(cfg.families_per_cell,cfg);family=F(F.family_id==string(freeze.demo.family_id),:);
assert(height(family)==1 && family.split=="validation",'eba:DemoScope','The illustration is a declared validation family, separate from test performance.');
schedule=eba.continuousSchedule(family,cfg,Inf,string(freeze.demo.sequence_id),freeze.demo.seed,"final",1,freeze.stream_protocol.schedule_options(1));
result=eba.processStream(schedule,model,entry.settings,cfg,true);
assert(result.stopped_at_confirmation && result.final_state.phase=="CONFIRMED" && numel(result.confirmed_events)==1, ...
    'eba:DemoConfirmation','The frozen physical event must reach confirmation.');
assert(any(result.phases=="NORMAL") && any(result.phases=="SUSPECTED") && result.phases(end)=="CONFIRMED", ...
    'eba:DemoTransitions','The arrived prediction sequence must show NORMAL -> SUSPECTED -> CONFIRMED.');
event=result.confirmed_events(1);truth=result.truth;
assert(height(truth)==1 && event.class_id==truth.class_id && result.metrics.false_alarms==0 && result.metrics.n_matched_events==1, ...
    'eba:DemoTruth','Confirmation must match the injected class without a preceding false alarm.');
assert(all(result.window_predictions.decision_time_s>=result.window_predictions.window_end_s) && ...
    result.observed_until_s==event.confirmation_time_s && result.observed_until_s<=schedule.duration_s, ...
    'eba:DemoCausality','No window after confirmation may be processed.');
latency=event.confirmation_time_s-truth.start_s;
assert(latency>=0 && abs(latency-result.metrics.mean_latency_s)<1e-12 && all(isfinite(result.total_inference_times_s)), ...
    'eba:DemoTiming','Native latency must equal confirmation minus physical onset.');
stamp=string(datetime('now','TimeZone','UTC','Format',"yyyyMMdd'T'HHmmssSSS"));folder=fullfile(cfg.output,"confirmed_demo_"+stamp);
assert(~isfolder(folder));mkdir(folder);
paths=[fullfile(folder,'confirmed_event.json');fullfile(folder,'ground_truth.csv'); ...
    fullfile(folder,'window_predictions.csv');fullfile(folder,'results.mat'); ...
    fullfile(folder,'confirmation_timeline.png');fullfile(folder,'confirmation_summary.csv')];
eba.json(paths(1),event);writetable(truth,paths(2));writetable(result.window_predictions,paths(3));save(paths(4),'schedule','result','-v7.3');
indices=(0:round(result.observed_until_s*cfg.Fs)-1)';wave=eba.continuousSignal(schedule,indices,cfg);
f=figure('Visible','off');cleanupFigure=onCleanup(@() close(f));tiledlayout(3,1);
nexttile;plot(indices/cfg.Fs,wave);xline(truth.start_s,'k--','Physical onset');xline(event.confirmation_time_s,'r--','Confirmation');ylabel('Voltage (pu)');grid on;
nexttile;stairs(result.window_predictions.window_end_s,result.window_predictions.class_id);ylabel('Predicted class ID');grid on;
nexttile;stairs(result.window_predictions.window_end_s,result.window_predictions.confidence);yline(entry.settings.threshold_on,'k--');ylabel('Window score');xlabel('Simulation time (s)');grid on;
exportgraphics(f,paths(5),'Resolution',150);
summary=table(string(event.class),truth.start_s,event.estimated_start_s,event.confirmation_time_s,latency, ...
    abs(event.estimated_start_s-truth.start_s),event.confidence,numel(event.supporting_windows),result.metrics.false_alarms, ...
    'VariableNames',{'class','physical_start_s','estimated_start_s','confirmation_time_s','detection_latency_s', ...
    'absolute_start_error_s','minimum_supporting_window_score','supporting_windows','false_alarms'});writetable(summary,paths(6));
report=struct('status','PASS','scope','preselected clean validation illustration; test performance reported separately', ...
    'summary',table2struct(summary),'processed_windows',height(result.window_predictions), ...
    'stopped_at_first_confirmation',true,'end_estimate','right censored; no completed event end is inferred', ...
    'freeze_sha256',eba.hash(fullfile(cfg.root,'FROZEN_EXPERIMENT.json'),'file'));
eba.requireFrozen(cfg,'end');eba.manifest('confirmed_event_demo',cfg,struct('method',model.method,'classifier','SVM', ...
    'parameters',model.parameters,'hyperparameters',model.hyperparameters,'state_settings',entry.settings, ...
    'freeze_sha256',report.freeze_sha256,'report',report),paths);
fprintf('CONFIRMED_EVENT_DEMO_PASS class=%s latency_s=%.9g false_alarms=0 transitions=NORMAL,SUSPECTED,CONFIRMED\n',event.class,latency);
end
