function report=run_stream_reselection()
%RUN_STREAM_RESELECTION Re-rank the completed MATLAB validation grid without its old FP gate.
cfg=eba.config();
screenPath=fullfile(cfg.output,'stream_state_selection.csv');
windowPath=fullfile(cfg.output,'stream_window_development.mat');
assert(isfile(screenPath)&&isfile(windowPath),'eba:ReselectionInputs', ...
    'Completed MATLAB validation screening artifacts are required.');
T=readtable(screenPath,'TextType','string');W=load(windowPath,'models');
methods=["FFT","STFT","DWT","CWT","ST"];candidates=cell(numel(methods),1);rows=cell(numel(methods),1);
[status,sha]=system('git rev-parse HEAD');assert(status==0&&~isempty(regexp(strtrim(sha),'^[0-9a-f]{40}$','once')), ...
    'eba:ReselectionGit','A full Git SHA is required for candidate provenance.');sha=strtrim(sha);
base=struct('threshold_on',.7,'threshold_off',.5,'min_windows',2,'min_evidence_s',1/60, ...
    'recovery_windows',2,'refractory_s',0,'classes',cfg.classes,'method_version',cfg.method_version, ...
    'model_version','development','dataset_version',cfg.dataset_version,'git_commit',sha, ...
    'sequence_id','reselection_candidate','confidence_calibrated',true);
for m=1:numel(methods)
    take=find(T.method==methods(m)&isfinite(T.event_f1)&isfinite(T.stream_RTF_p95)&T.stream_RTF_p95<=1);
    assert(~isempty(take),'eba:ReselectionFeasibility','No RTF-feasible candidate for %s.',methods(m));
    objective=[T.event_f1(take),-T.false_alarms_per_minute(take),-T.matched_latency_s(take),-T.stream_RTF_p95(take)];
    front=eba.pareto(objective,ones(1,4));take=take(front);
    rank=[-T.event_f1(take),T.matched_latency_s(take),take];[~,order]=sortrows(rank,[1 2 3]);ix=take(order(1));r=T(ix,:);
    w=find(cfg.stream_window_cycles==r.window_cycles);assert(isscalar(w),'eba:ReselectionWindow','Unknown selected window.');
    model=W.models{m,w};model.hop_samples=max(1,round(model.window_samples*r.hop_fraction));
    settings=base;settings.threshold_on=r.threshold_on;settings.threshold_off=max(.1,r.threshold_on-.2);
    settings.min_windows=r.min_windows;settings.min_evidence_s=r.evidence_cycles/60;settings.model_version=model.model_version;
    candidates{m}=struct('method_index',m,'window_index',w,'hop_fraction',r.hop_fraction, ...
        'settings',settings,'model',model,'event_f1',r.event_f1,'latency',r.matched_latency_s, ...
        'false_alarms_per_minute',r.false_alarms_per_minute,'rtf',r.stream_RTF_p95,'screening_row',ix);
    rows{m}=table(methods(m),r.window_cycles,r.hop_fraction,r.threshold_on,r.min_windows, ...
        r.event_f1,r.false_alarms_per_minute,r.matched_latency_s,r.stream_RTF_p95, ...
        'VariableNames',{'method','window_cycles','hop_fraction','threshold_on','min_windows', ...
        'event_f1','false_alarms_per_minute','matched_latency_s','stream_RTF_p95'});
end
summary=vertcat(rows{:});obj=[summary.event_f1,-summary.false_alarms_per_minute, ...
    -summary.matched_latency_s,-summary.stream_RTF_p95];summary.pareto=eba.pareto(obj,ones(1,4));
eligible=find(summary.pareto);[~,order]=sortrows([-summary.event_f1(eligible),summary.matched_latency_s(eligible),eligible],[1 2 3]);
chosen=eligible(order(1));summary.selected=false(height(summary),1);summary.selected(chosen)=true;
inputs=[string(screenPath);string(windowPath)];inputHashes=[eba.hash(screenPath,'file');eba.hash(windowPath,'file')];
out=fullfile(cfg.output,'stream_reselection_validation.mat');csv=fullfile(cfg.output,'stream_reselection_validation.csv');
save(out,'candidates','summary','chosen','inputs','inputHashes','-v7.3');writetable(summary,csv);
eba.manifest('stream_reselection_validation',cfg,struct('scope','reanalysis of completed validation-only MATLAB grids; test not loaded', ...
    'selection_rule','per-representation Pareto with event F1, false alarms/minute, latency and p95 RTF; require only RTF<=1; choose highest event F1 among nondominated representatives', ...
    'classifier','SVM','candidate_methods',methods,'source_artifacts',inputs,'source_sha256',inputHashes, ...
    'selected_method',summary.method(chosen),'selected_event_f1',summary.event_f1(chosen), ...
    'selected_false_alarms_per_minute',summary.false_alarms_per_minute(chosen)),{out,csv});
report=struct('status','PASS','scope','validation only','selected_method',summary.method(chosen), ...
    'selected_event_f1',summary.event_f1(chosen),'false_alarms_per_minute',summary.false_alarms_per_minute(chosen));
fprintf('STREAM_RESELECTION_PASS selected=%s eventF1=%.6f false_alarms_per_min=%.6f test_accessed=0\n', ...
    report.selected_method,report.selected_event_f1,report.false_alarms_per_minute);
end
