function report=run_solver_audit(methods,binaryLimit)
%RUN_SOLVER_AUDIT Native binary reruns recover diagnostics discarded by ECOC compaction.
% Equality is measured; a rerun is never presumed to certify the saved parent model.
cfg=eba.config();if nargin<1,methods=["FFT","STFT","DWT","CWT","ST"];end
if nargin<2,binaryLimit=Inf;end
methods=string(methods(:));assert(all(ismember(methods,["FFT","STFT","DWT","CWT","ST"])) && numel(unique(methods))==numel(methods));
assert(isscalar(binaryLimit) && binaryLimit>=1 && (binaryLimit==Inf || binaryLimit==fix(binaryLimit)));
rows=cell(0,1);diagnostics=cell(numel(methods),1);artifacts=strings(0,1);hyperparameters=cell(numel(methods),1);
for m=1:numel(methods)
    path=fullfile(cfg.output,"model_"+lower(methods(m))+"_svm.mat");stored=load(path,'model');model=stored.model;
    assert(model.kind=="SVM" && isa(model.fitted,'ClassificationECOC') && isprop(model.fitted,'X') && ...
        isprop(model.fitted,'Y'),'eba:SolverAudit','Audit requires the full native training object.');
    hyperparameters{m}=model.hyperparameters;native=model.fitted;Z=native.X;coding=native.CodingMatrix;binaryY=native.BinaryY;
    assert(isnumeric(Z) && isnumeric(native.Y) && all(isfinite(Z),'all'),'eba:SolverAudit','Native fitted input is required.');
    old=rng;restore=onCleanup(@() rng(old));rng(model.seed,'twister');
    diagnostics{m}=cell(size(coding,2),1);
    for b=1:min(binaryLimit,size(coding,2))
        y=binaryY(:,b);take=y~=0;neg=find(coding(:,b)==-1);pos=find(coding(:,b)==1);
        prior=[sum(native.Prior(neg)),sum(native.Prior(pos))];cost=native.Cost;cost(isnan(cost))=0;
        if all(prior>0)
            prior=[sum(native.Prior(neg))*native.Prior(neg)*cost(neg,pos)*native.Prior(pos)', ...
                sum(native.Prior(pos))*native.Prior(pos)*cost(pos,neg)*native.Prior(neg)'];
        end
        timer=tic;full=fitcsvm(Z(take,:),y(take),'KernelFunction',char(model.hyperparameters.kernel), ...
            'BoxConstraint',model.hyperparameters.box_constraint,'KernelScale',model.hyperparameters.kernel_scale, ...
            'Standardize',false,'ClassNames',[-1 1],'Prior',prior,'Weights',native.W(take));seconds=toc(timer);
        compactParent=native.BinaryLearners{b};[~,parentScores]=predict(compactParent,Z(take,:));[~,rerunScores]=predict(full,Z(take,:));
        difference=max(abs(parentScores-rerunScores),[],'all');equal=isequal(parentScores,rerunScores);
        convergence=full.ConvergenceInfo;diagnostics{m}{b}=convergence;
        assert(isfield(convergence,'Converged') && isfield(convergence,'ReasonForConvergence'),'eba:SolverAudit','Native binary convergence diagnostics are missing.');
        rows{end+1}=table(methods(m),b,sum(take),logical(convergence.Converged),string(convergence.ReasonForConvergence), ...
            full.NumIterations,convergence.DeltaGradient,convergence.DeltaGradientTolerance, ...
            convergence.LargestKKTViolation,convergence.KKTTolerance,convergence.Gap,convergence.GapTolerance, ...
            difference,equal,seconds,string(eba.hash(path,'file')), ...
            'VariableNames',{'method','binary_learner','n_fit_records','rerun_converged','convergence_reason', ...
            'iterations','delta_gradient','delta_gradient_tolerance','largest_KKT_violation','KKT_tolerance', ...
            'primal_dual_gap','gap_tolerance','max_training_score_difference','exact_parent_score_equality','audit_refit_time_s','parent_model_sha256'}); %#ok<AGROW>
        fprintf('NATIVE_SOLVER_AUDIT method=%s learner=%d/%d converged=%d exact_parent=%d iterations=%d\n', ...
            methods(m),b,size(coding,2),convergence.Converged,equal,full.NumIterations);
    end
    clear restore
end
summary=vertcat(rows{:});stamp=string(datetime('now','TimeZone','UTC','Format',"yyyyMMdd'T'HHmmssSSS"));
id="native_solver_audit_"+stamp;paths=[fullfile(cfg.output,id+".csv");fullfile(cfg.output,id+".mat")];
writetable(summary,paths(1));save(paths(2),'summary','diagnostics','-v7.3');artifacts=[artifacts;paths];
report=struct('scope','train-only native binary diagnostic reruns; no validation or test prediction access', ...
    'n_binary_reruns',height(summary),'n_converged_reruns',sum(summary.rerun_converged), ...
    'n_exact_parent_matches',sum(summary.exact_parent_score_equality), ...
    'convergence_claim','Rerun diagnostics apply to saved parent predictions only where native scores match exactly on all fitted rows; criterion is native default numerical tolerance, not exact mathematical optimum', ...
    'solver_change',false,'methods',methods,'classifier','SVM','hyperparameters',{hyperparameters}, ...
    'parameters',struct('solver','SMO','iteration_limit',1e6,'delta_gradient_tolerance',1e-3, ...
        'KKT_tolerance',0,'gap_tolerance',0,'shrinkage_period',0,'standardization','external fit-only; native disabled'), ...
    'rerun_policy','same kernel, C, scale, native class priors, observation weights and sample order; exact-parent equality measured on all fitted rows');
eba.manifest(id,cfg,report,artifacts);
assert(all(summary.rerun_converged & summary.exact_parent_score_equality),'eba:SolverAuditReview', ...
    'Native convergence or equality is incomplete; preserve the evidence and return to numerical development before freeze.');
fprintf('NATIVE_SOLVER_AUDIT_PASS binary_learners=%d test_accessed=0\n',height(summary));
end
