function verify_six_model_streambench()
%VERIFY_SIX_MODEL_STREAMBENCH Guard coverage and matched-workload evidence.
cfg=eba.config();path=fullfile(cfg.output,'six_model_stream','six_model_stream_validation.csv');
T=readtable(path,'TextType','string');assert(height(T)==6&&all(T.complete), ...
    'eba:SixVerifyCoverage','Expected six full-validation rows.');
assert(sum(T.classifier=="SVM")==3&&sum(T.classifier=="RF")==3&& ...
    isequal(sort(T.method(T.classifier=="SVM")),sort(["FFT";"STFT";"DWT"]))&& ...
    isequal(sort(T.method(T.classifier=="RF")),sort(["FFT";"ST";"CWT"])), ...
    'eba:SixVerifyTracks','The low-cost and heavy candidate sets changed.');
for i=1:height(T)
    assert(isfinite(T.event_f1(i))&&isfinite(T.event_f1_ci_low(i))&& ...
        isfinite(T.false_alarms_per_minute(i))&&isfinite(T.matched_latency_s(i)), ...
        'eba:SixVerifyMetrics','Candidate has missing temporal outcomes.');
    p=fullfile(cfg.output,'six_model_stream',"validation_"+lower(T.classifier(i))+"_"+lower(T.method(i))+".json");
    R=jsondecode(fileread(p));assert(R.n_sequences==864&&R.n_independent_clusters==864&& ...
        R.noise_snr_db==20&&R.noise_realization==1&& ...
        abs(R.f1-T.event_f1(i))<1e-12,'eba:SixVerifyWorkload','Candidate validation workload differs.');
    if T.classifier(i)=="SVM",runtime=fullfile(cfg.output,"runtime_reselection_stream_"+lower(T.method(i))+".json");
    else,runtime=fullfile(cfg.output,'six_model_stream',"runtime_rf_"+lower(T.method(i))+".json");end
    assert(isfile(runtime),'eba:SixVerifyRuntime','Every candidate needs a matched fresh-session runtime artifact.');
    Q=jsondecode(fileread(runtime));assert(isfinite(Q.total_p95_s)&&isfinite(Q.total_p99_s)&& ...
        isfinite(Q.peak_process_RSS_bytes)&&isfinite(Q.model_serialized_bytes), ...
        'eba:SixVerifyRuntime','Candidate runtime, memory or model size is missing.');
end
fprintf('SIX_MODEL_STREAMBENCH_PASS candidates=6 test_accessed=0\n');
end
