function verify_six_model_selection()
%VERIFY_SIX_MODEL_SELECTION Check all six candidates, shared runtime and selected identity.
cfg=eba.config();csv=fullfile(cfg.output,'six_model_stream','six_model_selection.csv');
json=fullfile(cfg.output,'six_model_stream','six_model_selection.json');T=readtable(csv,'TextType','string');R=jsondecode(fileread(json));
assert(height(T)==6&&sum(T.selected)==1&&all(T.complete)&&all(isfinite(T.runtime_p95_s))&& ...
    sum(T.classifier=="RF")==3&&sum(T.classifier=="SVM")==3&&~R.test_accessed&& ...
    R.n_sequences==864&&R.n_independent_clusters==864&&R.noise_snr_db==20, ...
    'eba:SixVerifySelection','Selection is incomplete or reached test.');
assert(T.method(T.selected)==string(R.selected_method)&&T.classifier(T.selected)==string(R.selected_classifier), ...
    'eba:SixVerifySelection','Selected candidate does not match the manifest report.');
assert(all(isfinite(T.stream_RTF_p95))&&all(isfinite(T.model_bytes))&& ...
    any(T.stream_RTF_p95>1 | T.model_bytes>5e6), ...
    'eba:SixVerifyCost','Runtime and size must be measured and slow/heavy models retained for comparison.');
fprintf('SIX_MODEL_SELECTION_PASS rows=6 selected=%s_%s test_accessed=0\n', ...
    R.selected_method,R.selected_classifier);
end
